name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # 매일 오전 3시 (KST)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2

      - name: Generate 3D Profile
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # 꼭 secrets.TOKEN 사용
          USERNAME: SeoHong23

      - name: Commit & Push
        run: |
          git config --global user.name "SeoHong23"
          git config --global user.email "ghd2408@naver.com"
          git add -A .
          git commit -m "generated"
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} HEAD:main
